### PR TITLE
Configurable StatVFS

### PR DESCRIPTION
**Pull request by vsinger**
Added configuration parameter for StatVFS extension usage as this is an extension which may not be active on a SFTP server.

### CODE REVIEW

**Comment by vsinger** [comment]
@arunvelsriram please let me know if there is anything else open for this PR to be accepted

**Comment by arunvelsriram** [comment]
Hi @vsinger. Sorry for the delayed response.

I just want to know what was the behaviour of `sftp-exporter` when the StatVFS extension is disabled before this change

**Comment by arunvelsriram** [comment]
@vsinger gentle bump on this :)

**Comment by vsinger** [comment]
@arunvelsriram It just fails to execute some commands (e.g. list files) which are needed for StatVFS to work. We had a customer SFTP server which had the StatVFS features disabled where we ran into some issues..

**Pull request merged**
